apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    #access modes https://i.stack.imgur.com/cJpY4.png
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi